### ISSUE TITLE
Size not available in mm

### ISSUE THREAD

**Issue by tobiasbp** [leechwort/knob-scale-generator#1]
Trying to design things not for screen use. It would be nice to be able to input the size of the knob in millimeters in stead of pixels. Also, if I show the size of an object in pixels, and then use that number for the size of the knob, the knob scale is a lot larger than I would expect?? How is the "knob size" parameter used?

**Comment by leechwort** [comment]
Knob size specifies size of internal border: when ticks are outside, this will specify radius of arc. When ticks are inside, knob size is radius of arc minus size of large ticks. All this was made to use panel hole diameter as starting point. Regarding pixel-mm conversion, I'm not sure that there is API to configure this in the plug-in, but I'll try to find what can I do.

**Comment by leechwort** [comment]
Fixed!
