### ISSUE TITLE
Feature request: Center on selected item

### ISSUE THREAD

**Issue by tobiasbp** [leechwort/knob-scale-generator#5]
It would be very practical, if the default center of the new scale, was be the currently selected object. With that feature, one could select an existing circle before using the extension, and the scale would be centered on that circle.

**Comment by leechwort** [comment]
Ok, I've found a little bit different way. Now there is additional option "Draw Centering Circle" - it just draws large circle around your scale. And you can go to menu "Object->Align", then select your generated scale and existing circle(we assume, that it is smaller then scale itself). In "Align" menu we select Relative to Smallest object, then use buttons to center scale:
![image](https://user-images.githubusercontent.com/4254582/43074766-1999aba6-8e87-11e8-9129-c56a2f69d403.png)

**Comment by tobiasbp** [comment]
Sounds like a good way to do it. Thanks!
